### ISSUE TITLE
Re-Minify on update

### ISSUE THREAD

**Issue by NebzHB** [Jeedom-Plugins-Extra/plugin-Optimize#13]
Bonjour à vous les Extra ;)
Excellente idée ce plugin tout d'abord !!!!

Ca serait sympatique d'avoir une option pour créer un cron ou une commande action pour reminifier.
(peut-etre ajouter un commentaire début du fichier pour vérifier qu'il a déjà été minifié ou garder la liste des fichiers + timestamp afin d'avoir un minifier différenciel et pas repasser par tous les fichiers)
Ou une reminification (sisi ca existe :-P) à l'update des plugins (je veux bien ajouter une commande dans mon plugin homebridge (dans install.php - homebridge_update()), si Optimize est là on re-minify le plugin par exemple) 
Meme si on est d'accord, cette minification devrait être fait au packaging de la stable...

**Comment by Sylvaner** [comment]
En effet, c'est une très bonne. Je vais voir pour implémenter cela. Merci

**Comment by Sylvaner** [comment]
La reminification est en place. Maintenant il faut détecter les mises à jour.

**Comment by NebzHB** [comment]
Un cron qui vérifierait s'il reste plusieurs \n dans un fichier .js que tous les plugins auraient ?

**Comment by Sylvaner** [comment]
Le problème est le parcours de l'ensemble des fichiers qui n'est quand même anodin sur un raspbery pi.

**Comment by NebzHB** [comment]
Pas besoin d'un parcours complet je pense, juste une liste de dossier dans plugins/*/desktop/nomPlugin.js qui je pense est obligatoire et dans tous les plugins + un .js pour le core

**Comment by Sylvaner** [comment]
On vient de me donner une alternative intéressante par les données en base de données :)

**Comment by Sylvaner** [comment]
Et voilà :) Il faudra sans doute désactiver et réactiver le plugin afin de lancer la procédure d'installation.
