### ISSUE TITLE
Minify JS do it wrong on some old nodejs libs

### ISSUE THREAD

**Issue by NebzHB** [Jeedom-Plugins-Extra/plugin-Optimize#14]
## Description
Une des libraires que j'utilise dans un de mes scripts utilise une librairie nodejs json-stringify-safe qui n'a plus été modifiée depuis 3 ans. il semblerait qu'ils n'aient pas bien terminé leurs lignes par des ; donc le minify se passe mal... serait-il possible d'ignorer les scripts nodejs et de s'en tenir au pure javascript web ?

**Comment by Sylvaner** [comment]
Hum... je vais voir pour trouver une meilleure librairie.
Pourrais-tu me fournir un fichier posant problème afin que je puisse effectuer des tests et essayer de trouver un pattern pour détecter le code javascript de NodeJS ?
Sinon je ferai une recherche qui se limitera aux répertoires javascript.

**Comment by NebzHB** [comment]
https://github.com/moll/json-stringify-safe/blob/master/stringify.js
ca concernait la ligne 18-19, il aime pas le tilde qui se retrouve à coté de l'indexOf.

le plus simple c'est d'exclure de ton tree tout ce qui est en dessous d'un dossier node_modules/ peu importe ou il se trouve

**Comment by Sylvaner** [comment]
L'exclusion est faite et sera dispo dans le prochain commit. Ce sera dans la master sous peu mais j'avance un peu sur les tests avant :)

**Comment by NebzHB** [comment]
Merci à toi !

**Comment by Sylvaner** [comment]
C'est bon, c'est dans le master
